name: CD

on:
    release:
        types: [ published ]
    push:
        branches: [ main ]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    build:
        name: Build prod images
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -   name: Checkout
                uses: actions/checkout@v6
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v4
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v4
            -   name: 'Login to GitHub Container Registry'
                uses: docker/login-action@v4
                with:
                    registry: ghcr.io
                    username: ${{github.actor}}
                    password: ${{secrets.GITHUB_TOKEN}}

            -   name: Docker Meta
                id: meta
                uses: docker/metadata-action@v6
                with:
                    images: |
                        ghcr.io/yohang/unlockey/backend-php
                        ghcr.io/yohang/unlockey/agent
                    tags: |
                        type=ref,event=branch
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}
                        type=raw,value=latest,enable=${{ github.event_name == 'release' }}

            - name: Build and Push
              uses: docker/bake-action@v7
              env:
                  EXTERNAL_USER_ID: 33
                  TAGS: "${{ steps.meta.outputs.version }}${{ github.event_name == 'release' && ',latest' || '' }}"
              with:
                  files: |
                      compose.yaml
                      docker-bake.hcl
                  targets: |
                      backend-php
                      agent
                  push: true
                  set: |
                      backend-php.cache-from=type=gha,scope=php-main
                      backend-php.cache-from=type=gha,scope=php-${{ github.ref_name }}
                      backend-php.cache-to=type=gha,scope=php-${{ github.ref_name }},mode=max
                      agent.cache-from=type=gha,scope=php-main
                      agent.cache-from=type=gha,scope=php-${{ github.ref_name }}
                      agent.cache-to=type=gha,scope=php-${{ github.ref_name }},mode=max

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: [ build ]
        environment: PROD
        if: github.event_name == 'release'
        env:
            DOCKER_HOST: 'ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}'
            APP_ENV: ${{ vars.APP_ENV }}
            APP_SECRET: ${{ secrets.APP_SECRET }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            CADDY_MERCURE_JWT_SECRET: ${{ secrets.CADDY_MERCURE_JWT_SECRET }}
            CADDY_MERCURE_URL: ${{ vars.CADDY_MERCURE_URL }}
            SERVER_NAME: ${{ vars.SERVER_NAME }}
            IMAGE_TAG: ${{ github.ref_name }}
            EXTERNAL_USER_ID: 33
        steps:
            -   name: Checkout
                uses: actions/checkout@v6
            -   name: Set up Docker Compose
                uses: docker/setup-compose-action@v2
                with:
                    version: latest
            -   name: Set up private key
                run: mkdir -p ~/.ssh && echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
            -   name: Trust remote host
                run: ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
            -   name: Docker login
                run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            -   name: Deploy to staging
                run: docker compose -p unlockey -f backend/compose.yaml up -d --pull always --wait backend-php --force-recreate --no-build --remove-orphans || (docker compose logs && exit 1)
            -   name: Prune server
                run: docker system prune -f --all --volumes
